version: '3'
services:
  postgres:
    image: postgres:alpine
    restart: 'no'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: development
      POSTGRES_DB: assesment-api
      PGDATA: /var/lib/postgres
